#HPM settings
#Wed Aug 05 20:33:31 CEST 2026
autoLockEnabled=true
autoLockMinutes=2
genAmbiguous=false
genLength=32
genLower=true
genNumbers=true
genSymbols=true
genUpper=true
lockOnFocusLoss=false
lockOnMinimize=false
lockoutExponential=true
lockoutThreshold=1
